name: CI/CD - backend
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - CI/CD
      - Tests
jobs:
  build:
    env:
        DATABASE_CONFIG: ${{ secrets.DATABASE_CONFIG }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
      continue-on-error: false
      working-directory: backend
    - name: Testing backend
      run: npm run test
      continue-on-error: false
      working-directory: backend
