name: Build and Test - Frontend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Go to frontend directory
      run: cd frontend
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
