name: Build and Test - Frontend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Go to frontend directory and install dependencies
      run: cd frontend && npm ci
      continue-on-error: true
    - name: Build frontend
      run: cd frontend && npm run build
